// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABPTvdvnUgKe7UX4o3NONSxOvKEgeqhbI',
    appId: '1:390053759038:web:d13ecef1cd55d14fb8a96f',
    messagingSenderId: '390053759038',
    projectId: 'ride-hailing-app-31cea',
    authDomain: 'ride-hailing-app-31cea.firebaseapp.com',
    storageBucket: 'ride-hailing-app-31cea.firebasestorage.app',
    measurementId: 'G-MGCLNQTLJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvpxxQv01ZgpDGn3jRv3skzZ-wb1k6ZoM',
    appId: '1:390053759038:android:fdf3a62741495eeab8a96f',
    messagingSenderId: '390053759038',
    projectId: 'ride-hailing-app-31cea',
    storageBucket: 'ride-hailing-app-31cea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8troAUVbj0uBGFyOuhddUIPH06uGZZoU',
    appId: '1:390053759038:ios:18609d7f442ca9edb8a96f',
    messagingSenderId: '390053759038',
    projectId: 'ride-hailing-app-31cea',
    storageBucket: 'ride-hailing-app-31cea.firebasestorage.app',
    iosBundleId: 'com.example.rideHailingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8troAUVbj0uBGFyOuhddUIPH06uGZZoU',
    appId: '1:390053759038:ios:18609d7f442ca9edb8a96f',
    messagingSenderId: '390053759038',
    projectId: 'ride-hailing-app-31cea',
    storageBucket: 'ride-hailing-app-31cea.firebasestorage.app',
    iosBundleId: 'com.example.rideHailingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABPTvdvnUgKe7UX4o3NONSxOvKEgeqhbI',
    appId: '1:390053759038:web:49794c599536a21cb8a96f',
    messagingSenderId: '390053759038',
    projectId: 'ride-hailing-app-31cea',
    authDomain: 'ride-hailing-app-31cea.firebaseapp.com',
    storageBucket: 'ride-hailing-app-31cea.firebasestorage.app',
    measurementId: 'G-4FT5BLW492',
  );
}
